# Generated by Django 4.0.2 on 2022-02-27 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadzenApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_customer',
            new_name='add_customer_details',
        ),
    ]
