# Generated by Django 4.0.2 on 2022-02-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadzenApp', '0002_rename_add_customer_add_customer_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('vehical_name', models.CharField(max_length=100)),
                ('vehical_number', models.IntegerField(max_length=100)),
                ('inventory_add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='add_customer_details',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
