# Generated by Django 4.0.2 on 2022-02-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadzenApp', '0003_inventory_alter_add_customer_details_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_details',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('vehical_name', models.CharField(max_length=100)),
                ('vehical_number', models.IntegerField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
